#!/usr/bin/env bash
# Task 0: Transfers a file from client to server
if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

scp -i $4 -o StrictHostKeyChecking=no $1 "$3"@"$2":~/
