#!/usr/bin/env bash
# Task 1: configures a new Ubuntu machine
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo /etc/init.d/nginx reload

sudo rm /var/www/html/*
sudo echo "Hello World" | sudo tee /var/www/html/index.html
