#!/usr/bin/env bash
# Task 1: configures a new Ubuntu machine
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo /etc/init.d/nginx restart

sudo rm /var/www/html/*
sudo echo "Hello World!" | sudo tee /var/www/html/index.html

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
firstLocation="^\tlocation / {"
secondLocation="\tlocation /redirect_me {\n\t\t return 301 $link;\n\t}\n\tlocation / {"

sudo sed -i "s|$firstLocation|$secondLocation|1" /etc/nginx/sites-available/default
