#!/usr/bin/env bash
# Task 1: Installs and configures HAproxy on lb-01 server
sudo apt-get update
sudo apt-get install -y haproxy
sudo /etc/init.d/haproxy start

sudo echo -e "\nfrontend haproxy-main\n\tbind *:80\n\toption forwardfor\n\tdefault_backend apache_webservers\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo -e "backend apache_webservers\n\tbalance roundrobin\n\tserver 4919-web-01 34.201.62.249:80 check\n\tserver 4919-web-02 3.89.119.171:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
